name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 完整克隆整个历史记录

    - name: Set Git Identity
      run: |
        git config --global user.name "KolinLoa"
        git config --global user.email "liukang861@yahoo.com"

    - name: Configure Git for GitLab
      env:
        GITLAB_URL: gitlab.com
        GITLAB_USERNAME: KolinLoa
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        git remote add gitlab https://${{ env.GITLAB_USERNAME }}:${{ env.GITLAB_TOKEN }}@$GITLAB_URL/KolinLoa/jx3-DrytronII.git
        git fetch gitlab main
        git merge gitlab/main --allow-unrelated-histories

    - name: Push to GitLab
      run: git push gitlab main
