name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Push to GitLab
      env:
        GITLAB_URL: https://gitlab.com
        GITLAB_USERNAME: KolinLoa
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        git remote add gitlab https://${{ env.GITLAB_USERNAME }}:${{ env.GITLAB_TOKEN }}@$GITLAB_URL/KolinLoa/jx3-DrytronII.git
        git push gitlab main
