name: Push to Gitea

on:
  push:
    branches:
      - main  # 根据需要修改为你想要监控的分支

jobs:
  push-to-gitea:
    runs-on: ubuntu-latest

    steps:
      # 检出当前 GitHub 仓库的代码
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      # 设置 Git 配置（在当前仓库范围内生效）
      - name: Set up Git configuration
        run: |
          git config --global user.name "KolinLoa"
          git config --global user.email "liukang861@yahoo.com"

      # 克隆 Gitea 仓库
      - name: Clone Gitea repository
        run: |
          git clone https://gitea.com/KolinLoa/jx3-DrytronII.git gitea-repo
        env:
          GIT_ASKPASS: /bin/echo
          GIT_PASSWORD: ${{ secrets.GITEA_TOKEN }}

      # 在 Gitea 仓库中设置 Git 配置
      - name: Set up Git configuration for Gitea repo
        run: |
          cd gitea-repo
          git config user.name "KolinLoa"
          git config user.email "liukang861@yahoo.com"

      # 使用 rsync 将 GitHub 仓库的文件复制到 Gitea 仓库中（排除 .git 目录）
      - name: Copy files to Gitea repo
        run: |
          rsync -av --exclude .git ./ gitea-repo/
          cd gitea-repo
          rm -rf gitea-repo  # 删除克隆仓库内的 `gitea-repo` 文件夹

      # 获取 GitHub 提交信息并提交到 Gitea
      - name: Commit and push to Gitea with GitHub commit message
        run: |
          cd gitea-repo  # 进入 Gitea 仓库
          git add .  # 添加所有更改的文件
          git commit -m "$(git log -1 --pretty=%B)"  # 使用 GitHub 提交的原始信息
          git push https://KolinLoa:${{ secrets.GITEA_TOKEN }}@gitea.com/KolinLoa/jx3-DrytronII.git
